*&---------------------------------------------------------------------*
*&  Include           ZPROJECT07_PO_TOP
*&---------------------------------------------------------------------*
TABLES : ZLFA107, ZEKKO07, ZEKPO07.
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'. "상수 선언

DATA : OK_CODE TYPE SY-UCOMM. "OK_CODE
DATA : GO_EVENT TYPE REF TO EVENT. "이벤트

DATA : GS_LFA1 LIKE ZLFA107.
DATA : GT_LFA1 LIKE TABLE OF GS_LFA1.

"헤더 구조체
TYPES : BEGIN OF TY_PO_HEADER,
        EBELN TYPE ZEKKO07-EBELN, "구매오더번호
        BUKRS TYPE ZEKKO07-BUKRS, "회사코드
        EKORG TYPE ZEKKO07-EKORG, "구매조직
        EKGRP TYPE ZEKKO07-EKGRP, "구매그룹
        LIFNR TYPE ZEKKO07-LIFNR, "구매처번호
        BEDAT TYPE ZEKKO07-BEDAT, "증빙일
        WAERS TYPE ZEKKO07-WAERS, "통화
        END OF TY_PO_HEADER.

"아이템 구조체
TYPES: BEGIN OF TY_PO_ITEM,
        EBELN TYPE ZEKPO07-EBELN, "구매오더번호
        EBELP TYPE ZEKPO07-EBELP, "품목
        MATNR TYPE ZEKPO07-MATNR, "자재번호
        MAKTX TYPE ZEKPO07-MAKTX, "자재명
        MENGE TYPE ZEKPO07-MENGE, "PO수량
        MEINS TYPE ZEKPO07-MEINS, "수량 단위
        NETPR TYPE ZEKPO07-NETPR, "단가 금액
        BPRME TYPE ZEKPO07-BPRME, "단가 단위
        WAERS TYPE ZEKPO07-WAERS, "통화
        MWSKZ TYPE ZEKPO07-MWSKZ, "세금코드*
        PRDAT TYPE ZEKPO07-PRDAT, "납품일
        WERKS TYPE ZEKPO07-WERKS, "플랜트
        LGORT TYPE ZEKPO07-LGORT, "저장위치
        VALID_MATNR  TYPE C, " 자재번호 유효성 플래그
        VALID_PRDAT  TYPE C, " 납품일 유효성 플래그
        VALID_WERKS  TYPE C, " 플랜트 유효성 플래그
        VALID_LGORT  TYPE C, " 저장위치 유효성 플래그
       END OF TY_PO_ITEM.

"조회 출력을 위한 ALV 구조체
DATA : BEGIN OF GS_SEARCH_DATA,
        EBELN TYPE ZEKKO07-EBELN, "구매오더번호
        BUKRS TYPE ZEKKO07-BUKRS, "회사코드
        EKORG TYPE ZEKKO07-EKORG, "구매조직
        EKGRP TYPE ZEKKO07-EKGRP, "구매그룹
        LIFNR TYPE ZEKKO07-LIFNR, "구매처번호
        BEDAT TYPE ZEKKO07-BEDAT, "증빙일
*       WAERS TYPE ZEKKO07-WAERS, "통화

        EBELP TYPE ZEKPO07-EBELP, "품목
        MATNR TYPE ZEKPO07-MATNR, "자재번호
        MAKTX TYPE ZEKPO07-MAKTX, "자재명
        MENGE TYPE ZEKPO07-MENGE, "PO수량
        MEINS TYPE ZEKPO07-MEINS, "수량 단위
        NETPR TYPE ZEKPO07-NETPR, "단가 금액
        BPRME TYPE ZEKPO07-BPRME, "단가 단위
        WAERS TYPE ZEKPO07-WAERS, "통화
        MWSKZ TYPE ZEKPO07-MWSKZ, "세금코드*
        PRDAT TYPE ZEKPO07-PRDAT, "납품일
        WERKS TYPE ZEKPO07-WERKS, "플랜트
        LGORT TYPE ZEKPO07-LGORT, "저장위치
        TOTAL_AMT  TYPE ZEKPO07-NETPR, " 총 금액
END OF GS_SEARCH_DATA.
DATA : GT_SEARCH_DATA LIKE TABLE OF GS_SEARCH_DATA.

"공통으로 입력받는 값
DATA : EKORG_IO TYPE ZEKKO07-EKORG. "구매조직
DATA : EKGRP_IO TYPE ZEKKO07-EKGRP. "구매그룹
DATA : WAERS_IO TYPE ZEKKO07-WAERS. "통화

DATA : GT_ALV_DATA TYPE TABLE OF TY_PO_ITEM.
DATA : GS_ALV_ROW TYPE TY_PO_ITEM.

DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER. " 스크린 200
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER. "스크린 300
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA: GT_FIELDCAT TYPE LVC_T_FCAT,       " 필드 카탈로그 테이블
      GS_FIELDCAT TYPE LVC_S_FCAT,       " 필드 카탈로그 구조체
      GS_LAYOUT TYPE LVC_S_LAYO,         " 필드 레이아웃 구조체
      GS_SORT TYPE LVC_S_SORT,
      GT_SORT TYPE LVC_T_SORT.

DATA : GS_SAVE_EKKO LIKE ZEKKO07.
DATA : GT_SAVE_EKKO LIKE TABLE OF GS_SAVE_EKKO.

DATA : GS_SAVE_EKPO LIKE ZEKPO07.
DATA : GT_SAVE_EKPO LIKE TABLE OF GS_SAVE_EKPO.
