*&---------------------------------------------------------------------*
*&  Include           ZPROJECT07_GR_TOP
*&---------------------------------------------------------------------*
TABLES : ZMKPF07, ZMSEG07, ZEKKO07, ZEKPO07.
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'. "상수 선언

DATA : OK_CODE TYPE SY-UCOMM. "OK_CODE
DATA : GO_EVENT TYPE REF TO EVENT. "이벤트

DATA : GS_EKKO LIKE ZEKKO07.

DATA : GS_GR_HEADER TYPE ZMKPF07.
DATA : GT_GR_HEADER LIKE TABLE OF GS_GR_HEADER.

DATA : GS_GR_ITEM TYPE ZMSEG07.
DATA : GT_GR_ITEM LIKE TABLE OF GS_GR_ITEM.


DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER. "도킹 컨테이너
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.  "그리드

DATA: GT_FIELDCAT TYPE LVC_T_FCAT,       " 필드 카탈로그 테이블
      GS_FIELDCAT TYPE LVC_S_FCAT,       " 필드 카탈로그 구조체
      GS_LAYOUT TYPE LVC_S_LAYO,         " 필드 레이아웃 구조체
      GT_SORT TYPE LVC_T_SORT,
      GS_SORT TYPE LVC_S_SORT.

"조회 출력을 위한 ALV 구조체
DATA : BEGIN OF GS_ALV_DATA,
  L_CHECK TYPE C LENGTH 4,
  EBELN TYPE ZEKPO07-EBELN, "구매오더번호
  EBELP TYPE ZEKPO07-EBELP, "품목번호(10,20,30 ...)
  LIFNR TYPE ZEKKO07-LIFNR, "구매처번호
  BEDAT TYPE ZEKKO07-BEDAT, "증빙일
  MATNR TYPE ZEKPO07-MATNR, "자재번호
  MAKTX TYPE ZEKPO07-MAKTX, "자재명
  MENGE TYPE ZEKPO07-MENGE, "수량
  MEINS TYPE ZEKPO07-MEINS, "단위
  NETPR TYPE ZEKPO07-NETPR, "단가 금액
  WAERS TYPE ZEKKO07-WAERS, "통화
  PRDAT TYPE ZEKPO07-PRDAT, "납품일
  WERKS TYPE ZEKPO07-WERKS, "플랜트
  LGORT TYPE ZEKPO07-LGORT, "저장위치
  BUKRS TYPE ZEKKO07-BUKRS, "회사코드
  END OF GS_ALV_DATA.
DATA : GT_ALV_DATA LIKE TABLE OF GS_ALV_DATA.

"입고된 데이터들을 가져오기 위한 구조체
DATA : BEGIN OF GS_STOCK,
  L_CHECK TYPE C LENGTH 4,
  MBLNR TYPE ZMKPF07-MBLNR, "입고문서번호
  MJAHR TYPE ZMKPF07-MJAHR, "회계연도
  BLART TYPE ZMKPF07-BLART, "전표유형
  BLDAT TYPE ZMKPF07-BLDAT, "증빙일
  BUDAT TYPE ZMKPF07-BUDAT, "전기일

  EBELN TYPE ZMSEG07-EBELN, "구매오더번호
  ZEILE TYPE ZMSEG07-ZEILE, "아이템번호(물품번호, EBELP)
  MATNR TYPE ZMSEG07-MATNR, "자재번호
  WERKS TYPE ZMSEG07-WERKS, "플랜트
  LGORT TYPE ZMSEG07-LGORT, "저장위치
  LIFNR TYPE ZMSEG07-LIFNR, "구매처번호
  WAERS TYPE ZMSEG07-WAERS, "통화
  MENGE TYPE ZMSEG07-MENGE, "수량
  MEINS TYPE ZMSEG07-MEINS, "단위
  BUKRS TYPE ZMSEG07-BUKRS, "회사코드
  GJAHR TYPE ZMSEG07-GJAHR, "회계연도
  BELNR TYPE ZMSEG07-BELNR, "전표번호
  SHKZG TYPE ZMSEG07-SHKZG, "차대변
  DMBTR TYPE ZMSEG07-DMBTR, "금액

  END OF GS_STOCK.
DATA : GT_STOCK LIKE TABLE OF GS_STOCK.
