*&---------------------------------------------------------------------*
*& Report ZEDR07_027
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_027.


DATA : BEGIN OF GS_STUDENT,
  ZPERNR LIKE ZEDT07_001-ZPERNR,
  ZCODE LIKE ZEDT07_001-ZCODE,
  ZKNAME LIKE ZEDT07_001-ZKNAME,
  ZENAME LIKE ZEDT07_001-ZENAME,
  ZGENDER LIKE ZEDT07_001-ZGENDER,
  ZGNAME TYPE C LENGTH 10,
  ZTEL LIKE ZEDT07_001-ZTEL,
  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT
      .

CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'F'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'A'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000002'.
GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'LEE'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01022223333'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'KANG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동동'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'F'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.

BREAK-POINT.

SORT GT_STUDENT BY ZCODE ZKNAME ZENAME ZGENDER.

DATA : STR TYPE STRING.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  STR = '성별구분'.
  BREAK-POINT.

  AT END OF ZENAME.
    STR = '변경사항'.
    BREAK-POINT.
  ENDAT.

  GS_STUDENT-ZGNAME = STR.
  MODIFY GT_STUDENT FROM GS_STUDENT TRANSPORTING ZGNAME.

BREAK-POINT.

ENDLOOP.


BREAK-POINT.

IF SY-SUBRC = 0.
  LOOP AT GT_STUDENT INTO GS_STUDENT.
    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZGNAME.
  ENDLOOP.
ENDIF.
