*&---------------------------------------------------------------------*
*&  Include           ZEDR07_PROJECT001_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  PARAMETERS : P_LIFNR TYPE ZLFA107-LIFNR MODIF ID M2. "구매처번호 -> 조회일때만 보임
  PARAMETERS : P_BUKRS TYPE ZLFB107-BUKRS DEFAULT 1000. "회사코드(1000 1개만 사용할 예정)
  PARAMETERS : P_KTOKK TYPE ZLFA107-KTOKK MODIF ID M1. "구매처그룹 -> 생성일때만 보임
SELECTION-SCREEN END OF BLOCK B1.


SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 USER-COMMAND UC1 DEFAULT 'X'. "구매처 생성
  PARAMETERS : P_R2 RADIOBUTTON GROUP R1. "조회
SELECTION-SCREEN END OF BLOCK B2.
