*&---------------------------------------------------------------------*
*&  Include           ZEDR07_PROJECT001_TOP
*&---------------------------------------------------------------------*

TABLES : ZLFA107, ZLFB107.
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'. "상수 선언

DATA : OK_CODE TYPE SY-UCOMM. "OK_CODE
DATA : GO_EVENT TYPE REF TO EVENT. "이벤트

" ALV 데이터 구조체
TYPES: BEGIN OF TY_ALV_ROW,
        LIFNR TYPE LIFNR, "구매처번호**
        BUKRS TYPE ZLFB107-BUKRS, "회사코드
        KTOKK TYPE ZLFA107-KTOKK, "구매처그룹
        NAME1 TYPE ZLFA107-NAME1, "구매처명
        LAND1 TYPE ZLFA107-LAND1, "국가키
        STCD1 TYPE ZLFA107-STCD1, "개인번호
        STCD2 TYPE ZLFA107-STCD2, "사업자번호
        STRAS TYPE ZLFA107-STRAS, "주소
        AKONT TYPE ZLFB107-AKONT, "계정
        ZTERM TYPE ZLFB107-ZTERM, "지급조건
        EKORG TYPE ZLFM107-EKORG, "구매조직
        EKGRP TYPE ZLFM107-EKGRP, "구매그룹
        WAERS TYPE ZLFM107-WAERS, "구매오더통화
        MWSKZ TYPE ZLFM107-MWSKZ, "세금코드
       END OF TY_ALV_ROW.

DATA : GT_ALV_DATA TYPE TABLE OF TY_ALV_ROW. "ALV 데이터 테이블
DATA : GS_ALV_ROW TYPE TY_ALV_ROW. "ALV 단일 행
DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.


DATA: LT_FIELDCAT TYPE LVC_T_FCAT,       " 필드 카탈로그 테이블
      LS_FIELDCAT TYPE LVC_S_FCAT.       " 필드 카탈로그 구조체

DATA : GS_SAVE_LFA1 LIKE ZLFA107.
DATA : GT_SAVE_LFA1 LIKE TABLE OF GS_SAVE_LFA1.

DATA : GS_SAVE_LFB1 LIKE ZLFB107.
DATA : GT_SAVE_LFB1 LIKE TABLE OF GS_SAVE_LFB1.

DATA : GS_SAVE_LFM1 LIKE ZLFM107.
DATA : GT_SAVE_LFM1 LIKE TABLE OF GS_SAVE_LFM1.
