*&---------------------------------------------------------------------*
*& Report ZEDR07_005
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_005.

DATA : BEGIN OF GS_STUDENT,
  ZCODE TYPE C LENGTH 10,
  ZKNAME TYPE C LENGTH 10,
  ZENAME TYPE C LENGTH 10,
  ZSUM TYPE I,
END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'LEE'.
GS_STUDENT-ZSUM = '10000'.
COLLECT GS_STUDENT INTO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'LEE'.
GS_STUDENT-ZSUM = '10000'.
COLLECT GS_STUDENT INTO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZCODE = 'SSU-03'.
GS_STUDENT-ZKNAME = '송중기'.
GS_STUDENT-ZENAME = 'SONG'.
GS_STUDENT-ZSUM = '10000'.
COLLECT GS_STUDENT INTO GT_STUDENT.

BREAK-POINT.
