*&---------------------------------------------------------------------*
*& Report ZEDR07_026
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_026.

DATA : BEGIN OF GS_STUDENT,
  ZPERNR LIKE ZEDT07_001-ZPERNR,
  ZCODE LIKE ZEDT07_001-ZCODE,
  ZKNAME LIKE ZEDT07_001-ZKNAME,
  ZENAME LIKE ZEDT07_001-ZENAME,
  ZGENDER LIKE ZEDT07_001-ZGENDER,
  ZGNAME TYPE C LENGTH 4,
  ZTEL LIKE ZEDT07_001-ZTEL,
  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112223'. "ZTEL 필드 값이 다름
APPEND GS_STUDENT TO GT_STUDENT.

"중복된 데이터를 삽입함 (단, ZTEL 필드의 값이 다름)

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000003'.
GS_STUDENT-ZCODE = 'SSU-03'.
GS_STUDENT-ZKNAME = '손예진'.
GS_STUDENT-ZENAME = 'SON'.
GS_STUDENT-ZGENDER = 'F'.
GS_STUDENT-ZTEL = '01033334444'.
APPEND GS_STUDENT TO GT_STUDENT.


CLEAR : GS_STUDENT.

BREAK-POINT.

SORT GT_STUDENT. "중복 삭제를 수행하기 전에 반드시 SORT로 정렬해야 함

BREAK-POINT.

*DELETE ADJACENT DUPLICATES FROM GT_STUDENT. "중복 제거
" -> 이경우 중복제거가 되지 않음. 하나의 필드라도 값이 다를시에는 중복이 제거되지 않는다

DELETE ADJACENT DUPLICATES FROM GT_STUDENT COMPARING ZCODE. "필드를 지정하여 중복제거
" 지정한 필드의 값이 같은 경우에 중복이 제거됨
" 즉, ZCODE의 값으로 중복을 판단하여 이 필드의 값이 같으면 중복이 제거

IF SY-SUBRC = 0.
  LOOP AT GT_STUDENT INTO GS_STUDENT.
    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZGENDER.
  ENDLOOP.
ENDIF.

BREAK-POINT.
