*&---------------------------------------------------------------------*
*& Report ZEDR07_002
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_002.

DATA : BEGIN OF GS_STUDENT,
  ZCODE TYPE C LENGTH 10,
  ZKNAME TYPE C LENGTH 10,
  ZENAME TYPE C LENGTH 10,
END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'LEE'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_STUDENT-ZCODE = 'SSU-03'.
GS_STUDENT-ZKNAME = '송중기'.
GS_STUDENT-ZENAME = 'SONG'.
APPEND GS_STUDENT TO GT_STUDENT.

BREAK-POINT.

SORT GT_STUDENT.

BREAK-POINT.

SORT GT_STUDENT DESCENDING.

BREAK-POINT.

SORT GT_STUDENT BY ZKNAME.

BREAK-POINT.

SORT GT_STUDENT BY ZKNAME DESCENDING.

BREAK-POINT.

GS_STUDENT-ZCODE = 'SSU-04'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'LEE'.
APPEND GS_STUDENT TO GT_STUDENT.

SORT GT_STUDENT BY ZKNAME ZCODE DESCENDING.

BREAK-POINT.
