*&---------------------------------------------------------------------*
*& Report ZEDR07_031
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_031.

DATA : GS_STUDENT TYPE ZEDT07_001.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

DATA : BEGIN OF GS_MAJOR,
  ZPERNR LIKE ZEDT07_001-ZPERNR, "출석번호
  ZCODE LIKE ZEDT07_001-ZCODE, "학생코드
  ZMNAME LIKE ZEDT07_002-ZMNAME, "전공명
  END OF GS_MAJOR.

DATA : GT_MAJOR LIKE TABLE OF GS_MAJOR WITH NON-UNIQUE KEY ZCODE.

CLEAR : GS_MAJOR, GT_MAJOR.
CLEAR : GS_STUDENT, GT_STUDENT.

"서로 다른 인터널테이블에 각각의 데이터를 입력함
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_MAJOR-ZPERNR = '0000000001'.
GS_MAJOR-ZCODE = 'SSU-01'.
GS_MAJOR-ZMNAME = '경영학과'.
APPEND GS_MAJOR TO GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000002'.
GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'HOON'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01022223333'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_MAJOR-ZPERNR = '0000000002'.
GS_MAJOR-ZCODE = 'SSU-02'.
GS_MAJOR-ZMNAME = '컴퓨터학과'.
APPEND GS_MAJOR TO GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000003'.
GS_STUDENT-ZCODE = 'SSU-03'.
GS_STUDENT-ZKNAME = '현빈'.
GS_STUDENT-ZENAME = 'BIN'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01033334444'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_MAJOR-ZPERNR = '0000000003'.
GS_MAJOR-ZCODE = 'SSU-03'.
GS_MAJOR-ZMNAME = '프랑스어학과'.
APPEND GS_MAJOR TO GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000004'.
GS_STUDENT-ZCODE = 'SSU-04'.
GS_STUDENT-ZKNAME = '제니'.
GS_STUDENT-ZENAME = 'JENNY'.
GS_STUDENT-ZGENDER = 'F'.
GS_STUDENT-ZTEL = '01044445555'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_MAJOR-ZPERNR = '0000000004'.
GS_MAJOR-ZCODE = 'SSU-04'.
GS_MAJOR-ZMNAME = '경영학과'.
APPEND GS_MAJOR TO GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000005'.
GS_STUDENT-ZCODE = 'SSU-05'.
GS_STUDENT-ZKNAME = '정국'.
GS_STUDENT-ZENAME = 'KOOK'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01055556666'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_MAJOR-ZPERNR = '0000000005'.
GS_MAJOR-ZCODE = 'SSU-05'.
GS_MAJOR-ZMNAME = '미디어학과'.
APPEND GS_MAJOR TO GT_MAJOR.

BREAK-POINT.

"기본 READ구문
LOOP AT GT_STUDENT INTO GS_STUDENT.
  CLEAR : GS_MAJOR.
  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR. "필요한 데이터의 키 값을 GS_MAJOR에 담기
  READ TABLE GT_MAJOR FROM GS_MAJOR INTO GS_MAJOR. "GS_MAJOR의 정보를 얻어 결과값을 GS_MAJOR에 담아주기

  IF SY-SUBRC = 0.
    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.
  ELSE.
    WRITE :/ '데이터를 가져오지 못했습니다.'.
  ENDIF.
ENDLOOP.
