*&---------------------------------------------------------------------*
*&  Include           ZPROJECT07_IR_TOP
*&---------------------------------------------------------------------*
TABLES : ZEKKO07, ZEKPO07, ZRBKP07, ZRSEG07, ZLFB107.
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'. "상수 선언

DATA : OK_CODE TYPE SY-UCOMM. "OK_CODE
DATA : GO_EVENT TYPE REF TO EVENT. "이벤트

DATA : GS_IR_HEADER TYPE ZRBKP07.
DATA : GT_IR_HEADER LIKE TABLE OF GS_IR_HEADER.

DATA : GS_IR_ITEM TYPE ZRSEG07.
DATA : GT_IR_ITEM LIKE TABLE OF GS_IR_ITEM.

DATA : GS_EKKO LIKE ZEKKO07.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER. "도킹 컨테이너
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.  "그리드

DATA: GT_FIELDCAT TYPE LVC_T_FCAT,       " 필드 카탈로그 테이블
      GS_FIELDCAT TYPE LVC_S_FCAT,       " 필드 카탈로그 구조체
      GS_LAYOUT TYPE LVC_S_LAYO,         " 필드 레이아웃 구조체
      GT_SORT TYPE LVC_T_SORT,
      GS_SORT TYPE LVC_S_SORT.

"조회 출력을 위한 ALV 구조체
DATA : BEGIN OF GS_ALV_DATA,
  L_CHECK TYPE C LENGTH 4,
  BUKRS TYPE ZEKKO07-BUKRS, "회사코드
  EBELN TYPE ZEKPO07-EBELN, "구매오더번호
  EBELP TYPE ZEKPO07-EBELP, "품목번호(10,20,30 ...)
  MATNR TYPE ZEKPO07-MATNR, "자재번호
  MAKTX TYPE ZEKPO07-MAKTX, "자재명
  NETPR TYPE ZEKPO07-NETPR, "단가
  BPRME TYPE ZEKPO07-BPRME, "단가 단위
  MENGE TYPE ZEKPO07-MENGE, "수량
  MEINS TYPE ZEKPO07-MEINS, "수량 단위
  DMBTR TYPE ZRSEG07-WRBTR, "공급가액(단가 × 수량)
  MWSTS TYPE ZRSEG07-MWSTS, "세액
  WRBTR TYPE ZRBKP07-WRBTR, "금액 (공급가액+세액)
  WAERS TYPE ZEKKO07-WAERS, "통화
  MWSKZ TYPE ZEKPO07-MWSKZ, "세금코드
  LIFNR TYPE ZEKKO07-LIFNR, "구매처번호
  END OF GS_ALV_DATA.
DATA : GT_ALV_DATA LIKE TABLE OF GS_ALV_DATA.

"입고된 데이터들을 가져오기 위한 구조체
DATA : BEGIN OF GS_RECEIVED_GOODS,
  L_CHECK TYPE C LENGTH 4,
  BELNR TYPE ZRBKP07-BELNR, "송장문서번호
  GJAHR TYPE ZRBKP07-GJAHR, "송장연도
  BUZEI TYPE ZRSEG07-BUZEI, "송장 아이템 번호
  BUKRS TYPE ZEKKO07-BUKRS, "회사코드
  EBELN TYPE ZEKPO07-EBELN, "구매오더번호
  EBELP TYPE ZEKPO07-EBELP, "품목번호(10,20,30 ...)
  MATNR TYPE ZEKPO07-MATNR, "자재번호
  MAKTX TYPE ZEKPO07-MAKTX, "자재명
  NETPR TYPE ZEKPO07-NETPR, "단가
  MENGE TYPE ZEKPO07-MENGE, "수량
  DMBTR TYPE ZRSEG07-WRBTR, "공급가액(단가 × 수량)
  MWSTS TYPE ZRSEG07-MWSTS, "세액
  WRBTR TYPE ZRBKP07-WRBTR, "금액 (공급가액+세액)
  WAERS TYPE ZEKKO07-WAERS, "통화
  MWSKZ TYPE ZEKPO07-MWSKZ, "세금코드
  LIFNR TYPE ZEKKO07-LIFNR, "구매처번호
  END OF GS_RECEIVED_GOODS.
DATA : GT_RECEIVED_GOODS LIKE TABLE OF GS_RECEIVED_GOODS.
