*&---------------------------------------------------------------------*
*& Report ZEDR07_069
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_069 MESSAGE-ID ZMED07.

TABLES : ZEDT07_001.
"SELECT-OPTIONS 사용시 FOR 뒤에 나오는 테이블을 TABLES로 반드시 선언

DATA : BEGIN OF GS_STUDENT.
  INCLUDE TYPE ZEDT07_001.
  DATA : END OF GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

"블록 구분 나누기
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE.
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01'. "DEFAULT 기본값 설정 가능
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ. "입력된 이외 값 조회
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION BT. "DEFAULT의 DATA가 1개일때는 BT 사용 불가
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS.
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' NO-EXTENSION.
  " NO INTERVALS를 통해 상한 값을 보여주지 않음
*  SELECT-OPTIONS : S_ZCODE FOR ZEDT07_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3. "길이 조정
SELECTION-SCREEN END OF BLOCK B1.

IF S_ZCODE IS INITIAL.
*  MESSAGE E000.
  MESSAGE I000."I는 경고성이라서 실행은 됨
  EXIT. "I사용시 실행을 막고싶을 때
ENDIF.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  PARAMETERS : P_ZGEN LIKE ZEDT07_001-ZGENDER.
SELECTION-SCREEN END OF BLOCK B2.

SELECT * FROM ZEDT07_001
  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT
  WHERE ZCODE IN S_ZCODE
  AND ZGENDER = P_ZGEN.

IF GT_STUDENT[] IS NOT INITIAL.
  CLEAR : GS_STUDENT.
  LOOP AT GT_STUDENT INTO GS_STUDENT.
    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.
  ENDLOOP.
ELSE.
  MESSAGE I001. "데이터 없을 시에, 없다는 메세지 출력해주기
  EXIT.
*  WRITE :/ '데이터 없음'.
ENDIF.
