*&---------------------------------------------------------------------*
*&  Include           ZEDR07_HW002_TOP
*&---------------------------------------------------------------------*

"데이터 가져올 DB 선언
TABLES : ZEDT07_100, ZEDT07_101, ZEDT07_001, ZEDT07_102.
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'. "상수 선언
RANGES : R_REFUND FOR ZEDT07_100-ZRET_FG. "반품 조건 조회를 위한 RANGES

"주문 내역 구조체
DATA : BEGIN OF GS_ORDER,
  ZORDNO TYPE ZEDT07_100-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_100-ZIDCODE, "회원 ID
  ZMATNR TYPE ZEDT07_100-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_100-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_100-ZMTART, "제품유형
  ZVOLUM TYPE ZEDT07_100-ZVOLUM, "수량
  VRKME TYPE ZEDT07_100-VRKME,"단위
  ZNSAMT TYPE ZEDT07_100-ZNSAMT, "판매금액
  ZSLAMT TYPE ZEDT07_100-ZSLAMT, "매출금액
  ZDCAMT TYPE ZEDT07_100-ZDCAMT, "할인금액
  ZSALE_FG TYPE ZEDT07_100-ZSALE_FG, "매출구분
  ZJDATE TYPE ZEDT07_100-ZJDATE, "판매일자
  ZRET_FG TYPE ZEDT07_100-ZRET_FG, "반품구분
  ZRDATE TYPE ZEDT07_100-ZRDATE, "반품일
END OF GS_ORDER.
DATA : GT_ORDER LIKE TABLE OF GS_ORDER. "인터널테이블

"주문내역 ALV출력용
DATA : BEGIN OF GS_ORDER_ALV,
  ZCOLOR TYPE C LENGTH 4, "신호등 색상을 표기하기 위한 변수
  ZORDNO TYPE ZEDT07_100-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_100-ZIDCODE, "회원 ID
  ZMATNR TYPE ZEDT07_100-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_100-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_100-ZMTART, "제품유형
  ZMTART_NAME TYPE STR, "제품유형 이름
  ZVOLUM TYPE ZEDT07_100-ZVOLUM, "수량
  VRKME TYPE ZEDT07_100-VRKME,"단위
  ZNSAMT TYPE ZEDT07_100-ZNSAMT, "판매금액
  ZSLAMT TYPE ZEDT07_100-ZSLAMT, "매출금액
  ZDCAMT TYPE ZEDT07_100-ZDCAMT, "할인금액
  ZSALE_FG TYPE ZEDT07_100-ZSALE_FG, "매출구분
  ZSALE_FG_NAME TYPE STR, "매출구분 이름
  ZJDATE TYPE ZEDT07_100-ZJDATE, "판매일자
  ZRET_FG TYPE ZEDT07_100-ZRET_FG, "반품구분
  ZRET_FG_NAME TYPE STR, "반품구분 이름
  ZRDATE TYPE ZEDT07_100-ZRDATE, "반품일
  END OF GS_ORDER_ALV.
DATA : GT_ORDER_ALV LIKE TABLE OF GS_ORDER_ALV. "인터널테이블

"배송내역 구조체
DATA : BEGIN OF GS_DELIVERY,
  ZORDNO TYPE ZEDT07_101-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_101-ZIDCODE, "회원ID
  ZMATNR TYPE ZEDT07_101-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_101-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_101-ZMTART, "제품유형
  ZVOLUM TYPE ZEDT07_101-ZVOLUM, "수량
  VRKME TYPE ZEDT07_101-VRKME, "단위
  ZSLAMT TYPE ZEDT07_101-ZSLAMT, "매출금액
  ZDFLAG TYPE ZEDT07_101-ZDFLAG, "배송현황
  ZDGUBUN TYPE ZEDT07_101-ZDGUBUN, "배송지역
  ZDDATE TYPE ZEDT07_101-ZDDATE, "배송일자
  ZRDATE TYPE ZEDT07_101-ZRDATE, "반품일자
  ZFLAG TYPE ZEDT07_101-ZFLAG, "반품표시
END OF GS_DELIVERY.
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.

"배송내역 ALV출력용
DATA : BEGIN OF GS_DELIVERY_ALV,
  ZCOLOR TYPE C LENGTH 4, "신호등 색상을 표기하기 위한 변수
  ZORDNO TYPE ZEDT07_101-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_101-ZIDCODE, "회원ID
  ZMATNR TYPE ZEDT07_101-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_101-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_101-ZMTART, "제품유형
  ZMTART_NAME TYPE STR, "제품유형 이름
  ZVOLUM TYPE ZEDT07_101-ZVOLUM, "수량
  VRKME TYPE ZEDT07_101-VRKME, "단위
  ZSLAMT TYPE ZEDT07_101-ZSLAMT, "매출금액
  ZDFLAG TYPE ZEDT07_101-ZDFLAG, "배송현황
  ZDFLAG_NAME TYPE STR, "배송현황 이름
  ZDGUBUN TYPE ZEDT07_101-ZDGUBUN, "배송지역
  ZDGUBUN_NAME TYPE STR, "배송지역 이름
  ZDDATE TYPE ZEDT07_101-ZDDATE, "배송일자
  ZRDATE TYPE ZEDT07_101-ZRDATE, "반품일자
  ZFLAG TYPE ZEDT07_101-ZFLAG, "반품표시
END OF GS_DELIVERY_ALV.
DATA : GT_DELIVERY_ALV LIKE TABLE OF GS_DELIVERY_ALV. "인터널테이블

"회원정보
"(SSU-00, 한국이름, 영문이름, 성별, 전화번호)
DATA : BEGIN OF GS_MEMBER,
  ZCODE TYPE ZEDT07_001-ZCODE,
  ZKNAME TYPE ZEDT07_001-ZKNAME,
  ZENAME TYPE ZEDT07_001-ZENAME,
  ZGENDER TYPE ZEDT07_001-ZGENDER,
  ZTEL TYPE ZEDT07_001-ZTEL,
END OF GS_MEMBER.
DATA : GT_MEMBER LIKE TABLE OF GS_MEMBER. "인터널 테이블

"회원정보 ALV 출력용
DATA : BEGIN OF GS_MEMBER_ALV,
  ZCODE TYPE ZEDT07_001-ZCODE,
  ZKNAME TYPE ZEDT07_001-ZKNAME,
  ZENAME TYPE ZEDT07_001-ZENAME,
  ZGENDER TYPE ZEDT07_001-ZGENDER,
  ZGENDER_NAME TYPE STR,
  ZTEL TYPE ZEDT07_001-ZTEL,
END OF GS_MEMBER_ALV.
DATA : GT_MEMBER_ALV LIKE TABLE OF GS_MEMBER_ALV. "인터널 테이블

"자재마스터 데이터 내용
"(제품번호(자재번호), 제품명, 플랜트명, 저장위치명, 자재유형명, 단가, 통화, 수량, 단위)
DATA : BEGIN OF GS_MARA,
  ZMATNR TYPE ZEDT07_102-ZMATNR,
  ZMATNAME TYPE ZEDT07_102-ZMATNAME,
  ZWERKS TYPE ZEDT07_102-ZWERKS,
  ZLGORT TYPE ZEDT07_102-ZLGORT,
  ZMTART TYPE ZEDT07_102-ZMTART,
  STPRS TYPE ZEDT07_102-STPRS,
  WAERS TYPE ZEDT07_102-WAERS,
  MENGE TYPE ZEDT07_102-MENGE,
  MEINS TYPE ZEDT07_102-MEINS,
END OF GS_MARA.
DATA : GT_MARA LIKE TABLE OF GS_MARA. "인터널 테이블

"자재마스터 ALV 출력용
DATA : BEGIN OF GS_MARA_ALV,
  ZMATNR TYPE ZEDT07_102-ZMATNR,
  ZMATNAME TYPE ZEDT07_102-ZMATNAME,
  ZWERKS TYPE ZEDT07_102-ZWERKS,
  ZWERKS_NAME TYPE STR, "플랜트 이름
  ZLGORT TYPE ZEDT07_102-ZLGORT,
  ZLGORT_NAME TYPE STR, "저장위치 이름
  ZMTART TYPE ZEDT07_102-ZMTART,
  ZMTART_NAME TYPE STR, "자재유형 이름
  STPRS TYPE ZEDT07_102-STPRS,
  WAERS TYPE ZEDT07_102-WAERS,
  MENGE TYPE ZEDT07_102-MENGE,
  MEINS TYPE ZEDT07_102-MEINS,
END OF GS_MARA_ALV.
DATA : GT_MARA_ALV LIKE TABLE OF GS_MARA_ALV. "인터널테이블

"OK-CODE
DATA : OK_CODE TYPE SY-UCOMM.

"도킹 컨테이너 객체 변수 선언
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

"SPLITTER 컨테이너 객체 변수 선언
DATA : GC_SPLITTER_TOP TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA : GC_SPLITTER_BOTTOM TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

"일반 컨테이너 객체 변수 선언
DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

"그리드 객체 변수
DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.

"필드 카탈로그
DATA : GS_FIELDCAT TYPE LVC_S_FCAT.
DATA : GT_FIELDCAT TYPE LVC_T_FCAT.
DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.
DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.

"정렬
DATA : GS_SORT TYPE LVC_S_SORT.
DATA : GT_SORT TYPE LVC_T_SORT.
DATA : GT_SORT2 TYPE LVC_T_SORT.
DATA : GT_SORT3 TYPE LVC_T_SORT.

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO.
