*&---------------------------------------------------------------------*
*& Report ZEDR01_HW003
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR01_HW003.

INCLUDE ZEDT01_HW003_CLS.
INCLUDE ZEDT01_HW003_TOP.
INCLUDE ZEDT01_HW003_SCR.
INCLUDE ZEDT01_HW003_F01.
INCLUDE ZEDT01_HW003_PBO.
INCLUDE ZEDT01_HW003_PAI.

INITIALIZATION.
"날짜 DEFAULT값.
PERFORM SET_DATE USING S_ZJDA-LOW S_ZJDA-HIGH.
APPEND S_ZJDA.
PERFORM SET_DATE USING S_ZDDA-LOW S_ZDDA-HIGH.
APPEND S_ZDDA.


"주문/배송 내역 스크린 제어.
AT SELECTION-SCREEN OUTPUT.
  PERFORM CHECK_SCREEN_GROUP.


START-OF-SELECTION.
  PERFORM CHECK_SCREEN_OUTPUT.
  PERFORM GET_DATA.
  PERFORM MODIFY_DATA.

END-OF-SELECTION.
  PERFORM CALL_SCREEN.
