*&---------------------------------------------------------------------*
*&  Include           ZEDT01_HW003_SCR
*&---------------------------------------------------------------------*


"주문내역 SELECTION-SCREEN
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  SELECT-OPTIONS : S_ZORD FOR ZEDT01_100-ZORDNO MODIF ID M1.    "주문번호
  PARAMETERS : P_ZID LIKE ZEDT01_100-ZIDCODE MODIF ID M1.       "회원ID
  SELECT-OPTIONS : S_ZMAT FOR ZEDT01_100-ZMATNR MODIF ID M1.    "제품번호
  SELECT-OPTIONS : S_ZJDA FOR ZEDT01_100-ZJDATE MODIF ID M1.    "주문일자
SELECTION-SCREEN END OF BLOCK B1.

"배송내역 SELECTION-SCREEN
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  SELECT-OPTIONS : S_ZORD2 FOR ZEDT01_101-ZORDNO MODIF ID M2.    "주문번호
  PARAMETERS : P_ZID2 LIKE ZEDT01_101-ZIDCODE MODIF ID M2.       "회원ID
  SELECT-OPTIONS : S_ZMAT2 FOR ZEDT01_101-ZMATNR MODIF ID M2.    "제품번호
  SELECT-OPTIONS : S_ZDDA FOR ZEDT01_101-ZDDATE MODIF ID M2.     "배송날짜
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.
  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND USC1.     "주문내역
  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.                                   "배송내역
SELECTION-SCREEN END OF BLOCK B3.

SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME.
  PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.               "반품내역포함
SELECTION-SCREEN END OF BLOCK B4.
