*&---------------------------------------------------------------------*
*&  Include           ZEDT01_HW003_TOP
*&---------------------------------------------------------------------*

TABLES : ZEDT01_100,ZEDT01_101.

"날짜 초기값 설정
RANGES : R_ZDATE FOR SY-DATUM.

DATA : GV_DATE LIKE SY-DATUM.

"체크구분
CONSTANTS : C_X TYPE C VALUE 'X'.

"클릭 행, 열 반환 변수
DATA : GV_ROW TYPE C,
      GV_COL TYPE C.

"데이터 실행 종료 변수
DATA : GV_EXIT_SCREEN TYPE C.

"행 수 확인
DATA : GC_T_INDEX_ROWS TYPE LVC_T_ROW.
DATA : GC_S_INDEX_ROWS TYPE LVC_S_ROW.
DATA : GV_COUNT TYPE I.
DATA : GV_CHECK TYPE C.

"PDF 파일
DATA : GV_FILENAME TYPE STRING,
      GT_PDF_CONTENT TYPE TABLE OF TLINE.


"주문관리 테이블
DATA : BEGIN OF GS_ORDER,
      ZORDNO LIKE ZEDT01_100-ZORDNO,      "주문번호
      ZIDCODE LIKE ZEDT01_100-ZIDCODE,    "회원ID
      ZMATNR LIKE ZEDT01_100-ZMATNR,      "제품번호
      ZMTART LIKE ZEDT01_100-ZMTART,      "제품유형
      ZMATNAME LIKE ZEDT01_100-ZMATNAME,  "제품명
      ZVOLUM LIKE ZEDT01_100-ZVOLUM,      "수량
      VOLUM LIKE ZEDT01_100-VOLUM,        "VOLUME
      VRKME LIKE ZEDT01_100-VRKME,        "SALES UNIT
      ZNSAMT LIKE ZEDT01_100-ZNSAMT,      "판매금액
      ZSLAMT LIKE ZEDT01_100-ZSLAMT,      "매출금액
      ZDCAMT LIKE ZEDT01_100-ZDCAMT,      "할인금액
      ZDC_FG LIKE ZEDT01_100-ZDC_FG,      "할인구분
      ZSALE_FG TYPE C LENGTH 2,           "매출구분
      ZRET_FG TYPE C LENGTH 4,            "반품구분
      ZJDATE LIKE ZEDT01_100-ZJDATE,      "판매일자
      ZRDATE LIKE ZEDT01_100-ZRDATE,      "반품일자
      ZCOLOR TYPE C LENGTH 4,             "신호등
      END OF GS_ORDER.
DATA : GT_ORDER LIKE TABLE OF GS_ORDER.
DATA : GT_ORDER_ALV LIKE TABLE OF GS_ORDER.
FIELD-SYMBOLS : <FS_ORDER> LIKE GS_ORDER.

"주문관리 PDF 테이블
DATA : BEGIN OF GS_ORDER_PDF,
      ZORDNO LIKE ZEDT01_100-ZORDNO,      "주문번호
      ZIDCODE LIKE ZEDT01_100-ZIDCODE,    "회원ID
      ZMATNR LIKE ZEDT01_100-ZMATNR,      "제품번호
      ZMATNAME LIKE ZEDT01_100-ZMATNAME,  "제품명
      ZSLAMT LIKE ZEDT01_100-ZSLAMT,      "매출금액
      ZJDATE LIKE ZEDT01_100-ZJDATE,      "판매일자
      END OF GS_ORDER_PDF.
DATA : GT_ORDER_PDF LIKE TABLE OF GS_ORDER_PDF.

"배송관리 테이블
DATA : BEGIN OF GS_DELIVER,
      ZORDNO LIKE ZEDT01_101-ZORDNO,      "주문번호
      ZIDCODE LIKE ZEDT01_101-ZIDCODE,    "회원ID
      ZMATNR LIKE ZEDT01_101-ZMATNR,      "제품번호
      ZMTART LIKE ZEDT01_101-ZMTART,      "제품유형
      ZMATNAME LIKE ZEDT01_101-ZMATNAME,  "제품명
      ZVOLUM LIKE ZEDT01_101-ZVOLUM,      "수량
      VOLUM LIKE ZEDT01_101-VOLUM,        "VOLUME
      VRKME LIKE ZEDT01_101-VRKME,        "SALES UNIT
      ZSLAMT LIKE ZEDT01_101-ZSLAMT,      "매출금액
      ZDFLAG TYPE C LENGTH 4,             "배송현황
      ZDGUBUN TYPE C LENGTH 3,            "배송지역
      ZDDATE LIKE ZEDT01_101-ZDDATE,      "배송일자
      ZRDATE LIKE ZEDT01_101-ZRDATE,      "반품일자
      ZFLAG LIKE ZEDT01_101-ZFLAG,        "체크구분
      ZCOLOR TYPE C LENGTH 4,             "신호등
      END OF GS_DELIVER.
DATA : GT_DELIVER LIKE TABLE OF GS_DELIVER.
DATA : GT_DELIVER_ALV LIKE TABLE OF GS_DELIVER.
FIELD-SYMBOLS : <FS_DELIVER> LIKE GS_DELIVER.

"배송관리 PDF 테이블
DATA : BEGIN OF GS_DELIVER_PDF,
      ZORDNO LIKE ZEDT01_101-ZORDNO,      "주문번호
      ZIDCODE LIKE ZEDT01_101-ZIDCODE,    "회원ID
      ZMATNR LIKE ZEDT01_101-ZMATNR,      "제품번호
      ZMATNAME LIKE ZEDT01_101-ZMATNAME,  "제품명
      ZSLAMT LIKE ZEDT01_101-ZSLAMT,      "매출금액
      ZDDATE LIKE ZEDT01_101-ZDDATE,      "배송일자
      END OF GS_DELIVER_PDF.
DATA : GT_DELIVER_PDF LIKE TABLE OF GS_DELIVER_PDF.


"필드 카탈로그
DATA : GS_FIELDCAT TYPE LVC_S_FCAT.
DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

"LAYOUT
DATA : GS_LAYOUT TYPE LVC_S_LAYO.

"SORT
DATA : GS_SORT TYPE LVC_S_SORT.
DATA : GT_SORT TYPE TABLE OF LVC_S_SORT.

"ALV 변수
DATA : OK_CODE TYPE SY-UCOMM.

"CONTAINER 변수
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

"GRID 변수
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

"EVENT 변수
DATA : GO_EVENT TYPE REF TO EVENT.

"PDF 다운로드 변수
DATA : GV_TEMP_DIR TYPE STRING,
      GV_FILE_PATH TYPE RLGRAP-FILENAME,
      GV_PDF_PATH TYPE RLGRAP-FILENAME,
      GS_WWWDATATAB LIKE WWWDATATAB,
      EXCEL TYPE OLE2_OBJECT,
      WORKBOOK TYPE OLE2_OBJECT,
      WORKSHEET TYPE OLE2_OBJECT,
      CELL TYPE OLE2_OBJECT,
      W_CELL TYPE OLE2_OBJECT.

"EXCEL 데이터 변수
TYPES : T_C(1500) TYPE C,
         T_DATA    TYPE TABLE OF T_C.
DATA : GT_EXCEL TYPE T_DATA,
         GS_EXCEL TYPE LINE OF T_DATA,
         DELI     TYPE C.

"FRONTEND_SERVICES
DATA : GC_FRONTEND TYPE REF TO CL_GUI_FRONTEND_SERVICES.
