*&---------------------------------------------------------------------*
*&  Include           ZEDT01_HW003_F01
*&---------------------------------------------------------------------*

FORM HANDLER_TOOLBAR USING P_OBJECT TYPE REF TO CL_ALV_EVENT_TOOLBAR_SET
                          P_INTERACTIVE.

  DATA : LS_TOOLBAR TYPE STB_BUTTON.
  CLEAR : LS_TOOLBAR.
  LS_TOOLBAR-FUNCTION = 'PDF'.
  LS_TOOLBAR-ICON = ICON_PRINT.
  LS_TOOLBAR-QUICKINFO = 'PDF 출력 버튼'.
  APPEND LS_TOOLBAR TO P_OBJECT->MT_TOOLBAR.

ENDFORM.

FORM HANDLER_USER_COMMAND USING P_UCOMM.

  CASE P_UCOMM.
    WHEN 'PDF'.
      IF P_R1 = C_X.
        PERFORM EXPORT_PDF.
      ENDIF.

  ENDCASE.

ENDFORM.

FORM EXPORT_PDF.

  PERFORM CHECK_ROW_LINES.
  CHECK GV_CHECK = 'X'.
  PERFORM GET_EXCEL_DATA.
  PERFORM WRITE_EXCEL_DATA.

ENDFORM.

FORM CHECK_ROW_LINES.

  CALL METHOD GC_GRID->GET_SELECTED_ROWS
  IMPORTING
    ET_INDEX_ROWS = GC_T_INDEX_ROWS.

  GV_COUNT = LINES( GC_T_INDEX_ROWS ).

  IF GV_COUNT > 1.
    MESSAGE '한 데이터만 선택 가능합니다.' TYPE 'E'.
    GV_CHECK = ''.
  ELSE.
    GV_CHECK = 'X'.
  ENDIF.

ENDFORM.

FORM GET_EXCEL_DATA.

  LOOP AT GC_T_INDEX_ROWS INTO GC_S_INDEX_ROWS.
    READ TABLE GT_ORDER_ALV INTO GS_ORDER INDEX GC_S_INDEX_ROWS-INDEX.
  ENDLOOP.

ENDFORM.

FORM WRITE_EXCEL_DATA.

  GV_FILE_PATH = 'C:\Users\USER\Desktop\과제3.xlsx'.
  GV_PDF_PATH = 'C:\Users\USER\Desktop\과제3.pdf'.

  SELECT SINGLE *
    FROM WWWDATA
    INTO CORRESPONDING FIELDS OF GS_WWWDATATAB
   WHERE OBJID = 'Z_EXCEL_TEMPLATE01'.


  CALL FUNCTION 'DOWNLOAD_WEB_OBJECT'
    EXPORTING
      KEY               = GS_WWWDATATAB
     DESTINATION        =  GV_FILE_PATH.

  CREATE OBJECT EXCEL 'EXCEL.APPLICATION'.

  CALL METHOD OF EXCEL 'WORKBOOKS' = WORKBOOK.
  CALL METHOD OF WORKBOOK 'OPEN'
    EXPORTING #1 = GV_FILE_PATH.

  GET PROPERTY OF EXCEL 'ACTIVESHEET' = WORKBOOK.

  "EXCEL 데이터 생성
  PERFORM APPEND_EXCEL_DATA.

  "return code
  DATA : LV_RC TYPE I.

  "값 대입
  CALL METHOD CL_GUI_FRONTEND_SERVICES=>CLIPBOARD_EXPORT
    EXPORTING
      NO_AUTH_CHECK        = ''           " Switch off Check for Access Rights "
    IMPORTING
      DATA                 = GT_EXCEL              " Data "
    CHANGING
      RC                   = LV_RC               " Return Code "
    EXCEPTIONS
      CNTL_ERROR           = 1                " Control error "
      ERROR_NO_GUI         = 2                " No GUI available "
      NOT_SUPPORTED_BY_GUI = 3                " GUI does not support this "
      NO_AUTHORITY         = 4                " Authorization check failed "
      OTHERS               = 5.

  CALL METHOD OF WORKBOOK 'PASTE'.

  CALL METHOD OF EXCEL 'ActiveWorkbook' = WORKBOOK.
  CALL METHOD OF WORKBOOK 'Save'.

  CALL METHOD OF WORKBOOK 'ExportAsFixedFormat'
  EXPORTING
    #1 = 0
    #2 = GV_PDF_PATH
    #3 = 0.

  CALL METHOD OF WORKBOOK 'CLOSE'.
  CALL METHOD OF EXCEL 'QUIT'.

  FREE OBJECT EXCEL.
  FREE OBJECT WORKBOOK.

ENDFORM.

FORM APPEND_EXCEL_DATA.

  DELI = CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.

  CLEAR : GS_EXCEL, GT_EXCEL.
  GS_EXCEL = |주문내역{ DELI }{ GS_ORDER-ZORDNO }|.
  APPEND GS_EXCEL TO GT_EXCEL.

  CLEAR : GS_EXCEL.
  GS_EXCEL = |회원ID{ DELI }{ GS_ORDER-ZIDCODE }|.
  APPEND GS_EXCEL TO GT_EXCEL.

  CLEAR : GS_EXCEL.
  GS_EXCEL = |제품번호{ DELI }{ GS_ORDER-ZMATNR }|.
  APPEND GS_EXCEL TO GT_EXCEL.

  CLEAR : GS_EXCEL.
  GS_EXCEL = |제품명{ DELI }{ GS_ORDER-ZMATNAME }|.
  APPEND GS_EXCEL TO GT_EXCEL.

  CLEAR : GS_EXCEL.
  GS_EXCEL = |매출금액{ DELI }{ GS_ORDER-ZSLAMT }|.
  APPEND GS_EXCEL TO GT_EXCEL.

  CLEAR : GS_EXCEL.
  GS_EXCEL = |판매일자{ DELI }{ GS_ORDER-ZJDATE }|.
  APPEND GS_EXCEL TO GT_EXCEL.


ENDFORM.


FORM SET_DATE USING LOW HIGH.

  "레인지 변수 사용
  R_ZDATE-SIGN = 'I'.
  R_ZDATE-OPTION = 'BT'.
  R_ZDATE-LOW = LOW.
  R_ZDATE-HIGH = HIGH.

  CONCATENATE SY-DATUM+0(4) '01' '01' INTO LOW.
  CONCATENATE SY-DATUM+0(6) '01' INTO HIGH.
  CALL FUNCTION 'RP_LAST_DAY_OF_MONTHS'
    EXPORTING
      DAY_IN                  = HIGH
   IMPORTING
     LAST_DAY_OF_MONTH       = HIGH.

ENDFORM.

FORM CHECK_SCREEN_GROUP.

  LOOP AT SCREEN.
    IF P_R1 = C_X.
      CASE SCREEN-GROUP1.
        WHEN 'M1'.
          SCREEN-ACTIVE = 1.
        WHEN 'M2'.
          SCREEN-ACTIVE = 0.
      ENDCASE.
    ELSEIF P_R2 = C_X.
      CASE SCREEN-GROUP1.
        WHEN 'M1'.
          SCREEN-ACTIVE = 0.
        WHEN 'M2'.
          SCREEN-ACTIVE = 1.
      ENDCASE.
    ENDIF.
    MODIFY SCREEN.
  ENDLOOP.

ENDFORM.

FORM CHECK_SCREEN_OUTPUT.
  IF P_R1 = C_X.
  "입력 결과 검사.
    PERFORM CHECK_SCREEN_OUTPUT_M1.
  ELSE.
    PERFORM CHECK_SCREEN_OUTPUT_M2.
  ENDIF.
ENDFORM.

FORM CHECK_SCREEN_OUTPUT_M1.
  IF ( S_ZORD IS INITIAL ) AND ( P_ZID IS INITIAL ).
    MESSAGE '입력이 되지 않았음' TYPE 'I'.
    GV_EXIT_SCREEN = C_X.
  ENDIF.
  IF ( P_ZID IS NOT INITIAL ) AND ( S_ZJDA IS INITIAL ).
    MESSAGE '주문일자 미입력' TYPE 'I'.
    GV_EXIT_SCREEN = C_X.
  ENDIF.
ENDFORM.

FORM CHECK_SCREEN_OUTPUT_M2.
  IF ( S_ZORD2 IS INITIAL ) AND ( P_ZID2 IS INITIAL ).
    MESSAGE '입력이 되지 않았음' TYPE 'I'.
    GV_EXIT_SCREEN = C_X.
  ENDIF.
ENDFORM.

FORM CREATE_OBJECT.
  "CONTAINER 변수 생성
  CREATE OBJECT GC_DOCKING
    EXPORTING
      REPID                       = SY-REPID
      DYNNR                       = SY-DYNNR
      EXTENSION                   = 2000
      .

  "GRID 변수 생성
  CREATE OBJECT GC_GRID
    EXPORTING
      I_PARENT          =   GC_DOCKING.

  CREATE OBJECT GC_FRONTEND.



ENDFORM.

FORM GET_DATA.

  "PARAMETER에 해당하는 모든 데이터 불러오기
  IF P_R1 = C_X.
    SELECT  *
      INTO CORRESPONDING FIELDS OF TABLE GT_ORDER
      FROM  ZEDT01_100
     WHERE  ZORDNO IN S_ZORD
        OR  ZIDCODE = P_ZID         "빈칸 허용
        OR  ZMATNR IN S_ZMAT
       AND  ZJDATE IN S_ZJDA.
  ELSEIF P_R2 = C_X.
    SELECT *
      INTO CORRESPONDING FIELDS OF TABLE GT_DELIVER
      FROM  ZEDT01_101
     WHERE  ZORDNO IN S_ZORD2
        OR  ZIDCODE = P_ZID2
        OR  ZMATNR IN S_ZMAT2
       AND  ZDDATE IN S_ZDDA.
  ENDIF.

ENDFORM.

FORM MODIFY_DATA.



  IF P_R1 = C_X.
    LOOP AT GT_ORDER ASSIGNING <FS_ORDER>.
      "신호등 표시
      PERFORM MODIFY_LIGHT USING <FS_ORDER>-ZSALE_FG CHANGING <FS_ORDER>-ZCOLOR.

      "제품 유형명
      PERFORM NAME_ZMTART CHANGING <FS_ORDER>-ZMTART.

      "매출구분
      PERFORM NAME_ZSALE_FG CHANGING <FS_ORDER>-ZSALE_FG.

      "반품 구분명
      PERFORM NAME_ZRET_FG CHANGING <FS_ORDER>-ZRET_FG.
    ENDLOOP.
    "반품 데이터 삭제.
    IF Z_CHECK NE C_X.
      DELETE GT_ORDER WHERE ZSALE_FG = '반품'.
    ENDIF.

    MOVE-CORRESPONDING GT_ORDER TO GT_ORDER_ALV.
  ELSEIF P_R2 = C_X.
    LOOP AT GT_DELIVER ASSIGNING <FS_DELIVER>.
      "신호등 표시
      PERFORM MODIFY_LIGHT USING <FS_DELIVER>-ZFLAG CHANGING <FS_DELIVER>-ZCOLOR.

      "제품 유형명
      PERFORM NAME_ZMTART CHANGING <FS_DELIVER>-ZMTART.

      "배송 현황
      PERFORM NAME_ZDFLAG CHANGING <FS_DELIVER>-ZDFLAG.

      "배송지역명
      PERFORM NAME_ZDGUBUN CHANGING <FS_DELIVER>-ZDGUBUN.
    ENDLOOP.

    MOVE-CORRESPONDING GT_DELIVER TO GT_DELIVER_ALV.

  ENDIF.




ENDFORM.

FORM MODIFY_LIGHT USING CHECK CHANGING COLOR.

  IF CHECK = '1' OR CHECK IS INITIAL.
    COLOR = '@08@'.
  ELSEIF CHECK = '2' OR CHECK = C_X.
    COLOR = '@0A@'.
  ENDIF.

ENDFORM.

FORM NAME_ZMTART CHANGING ZMTART.

  CASE ZMTART.
    WHEN '001'.
      ZMTART = '식품'.
    WHEN '002'.
      ZMTART = '상품'.
    WHEN '003'.
      ZMTART = '제품'.
    WHEN '004'.
      ZMTART = '의류'.
    WHEN '005'.
      ZMTART = '도서'.
    WHEN '006'.
      ZMTART = '서비스'.
   ENDCASE.

ENDFORM.

FORM NAME_ZSALE_FG CHANGING ZSALE_FG.

  CASE ZSALE_FG.
    WHEN '1'.
      ZSALE_FG = '매출'.
    WHEN '2'.
      ZSALE_FG = '반품'.
  ENDCASE.

ENDFORM.

FORM NAME_ZRET_FG CHANGING ZRET_FG.

  CASE ZRET_FG.
    WHEN '0'.
      ZRET_FG = ''.
    WHEN '1'.
      ZRET_FG = '단순변심'.
    WHEN '2'.
      ZRET_FG = '제품하자'.
    WHEN '3'.
      ZRET_FG = '배송문제'.
  ENDCASE.

ENDFORM.

FORM NAME_ZDFLAG  CHANGING ZDFLAG.

  CASE ZDFLAG.
    WHEN '1'.
      ZDFLAG = '배송시작'.
    WHEN '2'.
      ZDFLAG = '배송완료'.
    WHEN '3'.
      ZDFLAG = '배송완료'.
  ENDCASE.

ENDFORM.

FORM NAME_ZDGUBUN CHANGING ZDGUBUN.

  CASE ZDGUBUN.
    WHEN '1'.
      ZDGUBUN = '서울'.
    WHEN '2'.
      ZDGUBUN = '경기도'.
    WHEN '3'.
      ZDGUBUN = '충청도'.
    WHEN '4'.
      ZDGUBUN = '경상도'.
    WHEN '5'.
      ZDGUBUN = '강원도'.
    WHEN '6'.
      ZDGUBUN = '전라도'.
    WHEN '7'.
      ZDGUBUN = '제주도'.
   ENDCASE.

ENDFORM.

FORM CALL_SCREEN.
  IF P_R1 = 'X'.
    IF GV_EXIT_SCREEN = 'X'.
      EXIT.
    ELSE.
      CALL SCREEN 100.
    ENDIF.
  ELSEIF P_R2 = 'X'.
    IF GV_EXIT_SCREEN = 'X'.
      EXIT.
    ELSE.
      CALL SCREEN 200.
    ENDIF.
  ENDIF.
ENDFORM.


FORM FIELD_CATALOG.

  PERFORM FIELD_CATALOG_DEFAULT.

  IF P_R1 = C_X.
    PERFORM FIELD_CATALOG_ORDER.
  ELSEIF P_R2 = C_X.
    PERFORM FIELD_CATALOG_DELIVER.

  ENDIF.
ENDFORM.

FORM FIELD_CATALOG_DEFAULT.

  CLEAR : GS_FIELDCAT, GT_FIELDCAT.
  GS_FIELDCAT-COL_POS = 1.
  GS_FIELDCAT-FIELDNAME = 'ZCOLOR'.
  GS_FIELDCAT-SCRTEXT_M = '구분'.
  GS_FIELDCAT-ICON = 'X'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 2.
  GS_FIELDCAT-FIELDNAME = 'ZORDNO'.
  GS_FIELDCAT-SCRTEXT_M = '주문번호'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 3.
  GS_FIELDCAT-FIELDNAME = 'ZIDCODE'.
  GS_FIELDCAT-SCRTEXT_M = '회원ID'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 4.
  GS_FIELDCAT-FIELDNAME = 'ZMATNR'.
  GS_FIELDCAT-SCRTEXT_M = '제품번호'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 5.
  GS_FIELDCAT-FIELDNAME = 'ZMATNAME'.
  GS_FIELDCAT-SCRTEXT_M = '제품명'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 6.
  GS_FIELDCAT-FIELDNAME = 'ZMTART'.
  GS_FIELDCAT-SCRTEXT_M = '제품유형'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 7.
  GS_FIELDCAT-FIELDNAME = 'ZVOLUM'.
  GS_FIELDCAT-SCRTEXT_M = '수량'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 8.
  GS_FIELDCAT-FIELDNAME = 'VRKME'.
  GS_FIELDCAT-SCRTEXT_M = '단위'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.




ENDFORM.

FORM FIELD_CATALOG_ORDER.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 9.
  GS_FIELDCAT-FIELDNAME = 'ZNSAMT'.
  GS_FIELDCAT-SCRTEXT_M = '판매금액'.
  GS_FIELDCAT-CURRENCY = 'KRW'.
  GS_FIELDCAT-DO_SUM = 'X'.
  GS_FIELDCAT-OUTPUTLEN = 12.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 10.
  GS_FIELDCAT-FIELDNAME = 'ZSLAMT'.
  GS_FIELDCAT-SCRTEXT_M = '매출금액'.
  GS_FIELDCAT-CURRENCY = 'KRW'.
  GS_FIELDCAT-DO_SUM = 'X'.
  GS_FIELDCAT-OUTPUTLEN = 12.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 11.
  GS_FIELDCAT-FIELDNAME = 'ZDCAMT'.
  GS_FIELDCAT-SCRTEXT_M = '할인금액'.
  GS_FIELDCAT-CURRENCY = 'KRW'.
  GS_FIELDCAT-DO_SUM = 'X'.
  GS_FIELDCAT-OUTPUTLEN = 12.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 12.
  GS_FIELDCAT-FIELDNAME = 'ZSALE_FG'.
  GS_FIELDCAT-SCRTEXT_M = '매출구분'.
  GS_FIELDCAT-EMPHASIZE = 'X'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 13.
  GS_FIELDCAT-FIELDNAME = 'ZJDATE'.
  GS_FIELDCAT-SCRTEXT_M = '판매일자'.
  GS_FIELDCAT-OUTPUTLEN = 10.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CHECK Z_CHECK = C_X.
    CLEAR : GS_FIELDCAT.
    GS_FIELDCAT-COL_POS = 14.
    GS_FIELDCAT-FIELDNAME = 'ZRET_FG'.
    GS_FIELDCAT-SCRTEXT_M = '반품구분'.
    APPEND GS_FIELDCAT TO GT_FIELDCAT.

    CLEAR : GS_FIELDCAT.
    GS_FIELDCAT-COL_POS = 15.
    GS_FIELDCAT-FIELDNAME = 'ZRDATE'.
    GS_FIELDCAT-SCRTEXT_M = '반품일자'.
    GS_FIELDCAT-OUTPUTLEN = 10.
    APPEND GS_FIELDCAT TO GT_FIELDCAT.

ENDFORM.

FORM FIELD_CATALOG_DELIVER.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 9.
  GS_FIELDCAT-FIELDNAME = 'ZSLAMT'.
  GS_FIELDCAT-SCRTEXT_M = '매출금액'.
  GS_FIELDCAT-CURRENCY = 'KRW'.
  GS_FIELDCAT-DO_SUM = 'X'.
  GS_FIELDCAT-OUTPUTLEN = 12.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 10.
  GS_FIELDCAT-FIELDNAME = 'ZDFLAG'.
  GS_FIELDCAT-SCRTEXT_M = '배송현황'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 11.
  GS_FIELDCAT-FIELDNAME = 'ZDGUBUN'.
  GS_FIELDCAT-SCRTEXT_M = '배송지역'.
  GS_FIELDCAT-EMPHASIZE = 'X'.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CLEAR : GS_FIELDCAT.
  GS_FIELDCAT-COL_POS = 12.
  GS_FIELDCAT-FIELDNAME = 'ZDDATE'.
  GS_FIELDCAT-SCRTEXT_M = '배송일자'.
  GS_FIELDCAT-OUTPUTLEN = 10.
  APPEND GS_FIELDCAT TO GT_FIELDCAT.

  CHECK Z_CHECK = 'X'.
    CLEAR : GS_FIELDCAT.
    GS_FIELDCAT-COL_POS = 13.
    GS_FIELDCAT-FIELDNAME = 'ZRDATE'.
    GS_FIELDCAT-SCRTEXT_M = '반품일자'.
    GS_FIELDCAT-OUTPUTLEN = 10.
    APPEND GS_FIELDCAT TO GT_FIELDCAT.

    CLEAR : GS_FIELDCAT.
    GS_FIELDCAT-COL_POS = 14.
    GS_FIELDCAT-FIELDNAME = 'ZFLAG'.
    GS_FIELDCAT-SCRTEXT_M = '반품체크'.
    GS_FIELDCAT-EMPHASIZE = 'X'.
    GS_FIELDCAT-JUST = 'C'.
    APPEND GS_FIELDCAT TO GT_FIELDCAT.

ENDFORM.


FORM ALV_SORT.

  CLEAR : GS_SORT, GT_SORT.
  GS_SORT-SPOS = 3.
  GS_SORT-UP = 'X'.
  GS_SORT-FIELDNAME = 'ZIDCODE'.
  GS_SORT-SUBTOT = 'X'.
  APPEND GS_SORT TO GT_SORT.


ENDFORM.

FORM ALV_LAYOUT.

  CLEAR : GS_LAYOUT.
  GS_LAYOUT-ZEBRA = 'X'.
  GS_LAYOUT-SEL_MODE = 'A'.

ENDFORM.

FORM CALL_ALV.

IF P_R1 = C_X.
  CALL METHOD GC_GRID->SET_TABLE_FOR_FIRST_DISPLAY
    EXPORTING
       IS_LAYOUT                     = GS_LAYOUT
    CHANGING
      IT_OUTTAB                     = GT_ORDER_ALV
      IT_FIELDCATALOG               = GT_FIELDCAT
      IT_SORT                       = GT_SORT.

ELSEIF P_R2 = C_X.
  CALL METHOD GC_GRID->SET_TABLE_FOR_FIRST_DISPLAY
    EXPORTING
       IS_LAYOUT                     = GS_LAYOUT
    CHANGING
      IT_OUTTAB                     = GT_DELIVER_ALV
      IT_FIELDCATALOG               = GT_FIELDCAT
      IT_SORT                       = GT_SORT.

ENDIF.

ENDFORM.

FORM CLASS_EVENT.

  CREATE OBJECT GO_EVENT.

  SET HANDLER GO_EVENT->HANDLER_TOOLBAR FOR GC_GRID.
  SET HANDLER GO_EVENT->HANDLER_USER_COMMAND FOR GC_GRID.

ENDFORM.
