*&---------------------------------------------------------------------*
*& Report ZEDR07_073
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_073.

DATA : BEGIN OF GS_STUDENT.
  INCLUDE TYPE ZEDT07_001.
DATA : END OF GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*DATA : GV_ZCODE LIKE ZEDT07_001-ZCODE.
*DATA : GV_ZKNAME LIKE ZEDT07_001-ZKNAME.

*GV_ZCODE = 'SSU-01'.
*
*PERFORM GET_DATA USING GV_ZCODE
*                 CHANGING GV_ZKNAME.
*
*WRITE :/ GV_ZCODE.
*WRITE :/ GV_ZKNAME.

*FORM GET_DATA USING P_ZCODE TYPE C
*              CHANGING P_ZKNAME TYPE C.

*FORM GET_DATA USING P_ZCODE LIKE ZEDT07_001-ZCODE
*              CHANGING P_ZKNAME LIKE ZEDT07_001-ZKNAME.
*  SELECT SINGLE ZKNAME FROM ZEDT07_001
*    INTO P_ZKNAME
*    WHERE ZCODE = P_ZCODE.
*ENDFORM.


"PARAMETER 구조체
*GS_STUDENT-ZCODE = 'SSU-01'.
*
*PERFORM GET_DATA USING GS_STUDENT.
*
*WRITE :/ GS_STUDENT-ZCODE.
*WRITE :/ GS_STUDENT-ZKNAME.
*
*FORM GET_DATA USING PS_STUDENT STRUCTURE GS_STUDENT. "구조체 타입은 반드시 명시 필요
*  SELECT SINGLE ZKNAME FROM ZEDT07_001
*    INTO PS_STUDENT-ZKNAME
*    WHERE ZCODE = PS_STUDENT-ZCODE.
*ENDFORM.

"PARAMETER 인터널 테이블
*PERFORM GET_DATA USING GS_STUDENT
*                       GT_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.
ENDLOOP.

*FORM GET_DATA USING PS_STUDENT LIKE GS_STUDENT
*                    PT_STUDENT LIKE GT_STUDENT. "인터널 테이블 파라미터 전달시 반드시 명시
*
*  PS_STUDENT-ZCODE = 'SSU-01'.
*
*  SELECT SINGLE ZKNAME FROM ZEDT07_001
*  INTO PS_STUDENT-ZKNAME
*  WHERE ZCODE = GS_STUDENT-ZCODE.
*  APPEND PS_STUDENT TO PT_STUDENT.
*
*  PS_STUDENT-ZCODE = 'SSU-02'.
*
*  SELECT SINGLE ZKNAME FROM ZEDT07_001
*  INTO PS_STUDENT-ZKNAME
*  WHERE ZCODE = GS_STUDENT-ZCODE.
*  APPEND PS_STUDENT TO PT_STUDENT.
*
*ENDFORM.

*PERFORM GET_DATA USING GT_STUDENT.
*
*LOOP AT GT_STUDENT INTO GS_STUDENT.
*  WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.
*ENDLOOP.
*
*FORM GET_DATA USING PT_STUDENT TYPE STANDARD TABLE.
*  DATA : LS_STUDENT LIKE GS_STUDENT.
*
*  LS_STUDENT-ZCODE = 'SSU-01'.
*
*  SELECT SINGLE ZKNAME FROM ZEDT07_001
*  INTO LS_STUDENT-ZKNAME
*  WHERE ZCODE = LS_STUDENT-ZCODE.
*  APPEND LS_STUDENT TO PT_STUDENT.
*
*  LS_STUDENT-ZCODE = 'SSU-02'.
*
*  SELECT SINGLE ZKNAME FROM ZEDT07_001
*  INTO LS_STUDENT-ZKNAME
*  WHERE ZCODE = LS_STUDENT-ZCODE.
*  APPEND LS_STUDENT TO PT_STUDENT.
*
*ENDFORM.

PERFORM GET_DATA TABLES GT_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.
ENDLOOP.

FORM GET_DATA TABLES PT_STUDENT LIKE GT_STUDENT.
  DATA : LS_STUDENT LIKE GS_STUDENT.

  LS_STUDENT-ZCODE = 'SSU-01'.

  SELECT SINGLE ZKNAME FROM ZEDT07_001
  INTO LS_STUDENT-ZKNAME
  WHERE ZCODE = LS_STUDENT-ZCODE.
  APPEND LS_STUDENT TO PT_STUDENT.

  LS_STUDENT-ZCODE = 'SSU-02'.

  SELECT SINGLE ZKNAME FROM ZEDT07_001
  INTO LS_STUDENT-ZKNAME
  WHERE ZCODE = LS_STUDENT-ZCODE.
  APPEND LS_STUDENT TO PT_STUDENT.

ENDFORM.
