*&---------------------------------------------------------------------*
*& Report ZEDR07_074
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_074.

DATA : BEGIN OF GS_STUDENT.
  INCLUDE TYPE ZEDT07_001.
DATA : END OF GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

DATA : GV_ZCODE LIKE ZEDT07_001-ZCODE.
DATA : GV_ZKNAME LIKE ZEDT07_001-ZKNAME.

PERFORM GET_DATA CHANGING GT_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.
ENDLOOP.

FORM GET_DATA CHANGING PT_STUDENT LIKE GT_STUDENT.
  DATA : LS_STUDENT LIKE GS_STUDENT.

  LS_STUDENT-ZCODE = 'SSU-01'.

  SELECT SINGLE ZKNAME FROM ZEDT07_001
    INTO LS_STUDENT-ZKNAME
    WHERE ZCODE = LS_STUDENT-ZCODE.
  APPEND LS_STUDENT TO PT_STUDENT.

  LS_STUDENT-ZCODE = 'SSU-02'.

  SELECT SINGLE ZKNAME FROM ZEDT07_001
    INTO LS_STUDENT-ZKNAME
    WHERE ZCODE = LS_STUDENT-ZCODE.
  APPEND LS_STUDENT TO PT_STUDENT.

ENDFORM.
