*&---------------------------------------------------------------------*
*& Report ZEDR07_066
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_066.

DATA : BEGIN OF GS_SPFLI, "구조체 선언
  CARRID TYPE SPFLI-CARRID,
  CONNID TYPE SPFLI-CONNID,
  END OF GS_SPFLI.
DATA : GT_SPFLI LIKE TABLE OF GS_SPFLI. "인터널테이블 선언

DATA : BEGIN OF GS_SFLIGHT, "구조체 선언
  CARRID TYPE SFLIGHT-CARRID,
  CONNID TYPE SFLIGHT-CONNID,
  FLDATE TYPE SFLIGHT-FLDATE,
  PRICE TYPE SFLIGHT-PRICE,
  END OF GS_SFLIGHT.
DATA : GT_SFLIGHT LIKE TABLE OF GS_SFLIGHT. "인터널테이블 선언

"SELECT 문
SELECT CARRID
       CONNID
  FROM SPFLI
  INTO CORRESPONDING FIELDS OF TABLE GT_SPFLI
  WHERE CARRID LIKE 'A%'.
"SPFLI 테이블을 읽어서, CARRID가 A로 시작하는 값들을 인터널 테이블인 GT_SPFLI에 저장함

IF GT_SPFLI IS NOT INITIAL. "GT_SPFLI가 NULL 값이면 FULL SCAN으로 MEMORY DUMP가 일어나기 때문에 IF문 추가
  SELECT CARRID
         CONNID
         FLDATE
         PRICE
    FROM SFLIGHT
    INTO CORRESPONDING FIELDS OF TABLE GT_SFLIGHT
    FOR ALL ENTRIES IN GT_SPFLI
    WHERE CARRID = GT_SPFLI-CARRID "FOR ALL ENTRIES 구문의 WHERE 조건에는 LIKE, BETWEEN, IN과 같은 비교구문은 사용할 수 없음
    AND CONNID = GT_SPFLI-CONNID.
    "SFLIGHT 테이블을 읽어서  GT_SPFLI의 CARRID와 CONNID가 동일한 데이터들을 인터널테이블인 GT_SFLIGHT에 저장함
    "JOIN과 같은 역할을 함
ENDIF.

LOOP AT GT_SFLIGHT INTO GS_SFLIGHT.
  WRITE :/ GS_SFLIGHT-CARRID, GS_SFLIGHT-CONNID, GS_SFLIGHT-FLDATE, GS_SFLIGHT-PRICE.
ENDLOOP.
