*&---------------------------------------------------------------------*
*&  Include           ZEDR07_HW003_TOP
*&---------------------------------------------------------------------*

TABLES : ZEDT07_100, ZEDT07_101. "데이터 가져올 DB 선언
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'. "상수 선언
RANGES : R_REFUND FOR ZEDT07_100-ZRET_FG. "반품 조건 조회를 위한 RANGES

"주문 내역 구조체
DATA : BEGIN OF GS_ORDER,
  ZORDNO TYPE ZEDT07_100-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_100-ZIDCODE, "회원 ID
  ZMATNR TYPE ZEDT07_100-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_100-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_100-ZMTART, "제품유형
  ZVOLUM TYPE ZEDT07_100-ZVOLUM, "수량
  VRKME TYPE ZEDT07_100-VRKME,"단위
  ZNSAMT TYPE ZEDT07_100-ZNSAMT, "판매금액
  ZSLAMT TYPE ZEDT07_100-ZSLAMT, "매출금액
  ZDCAMT TYPE ZEDT07_100-ZDCAMT, "할인금액
  ZSALE_FG TYPE ZEDT07_100-ZSALE_FG, "매출구분
  ZJDATE TYPE ZEDT07_100-ZJDATE, "판매일자
  ZRET_FG TYPE ZEDT07_100-ZRET_FG, "반품구분
  ZRDATE TYPE ZEDT07_100-ZRDATE, "반품일
END OF GS_ORDER.
DATA : GT_ORDER LIKE TABLE OF GS_ORDER. "인터널테이블

"주문내역 ALV출력용
DATA : BEGIN OF GS_ORDER_ALV,
  ZCOLOR TYPE C LENGTH 4, "신호등 색상을 표기하기 위한 변수
  ZORDNO TYPE ZEDT07_100-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_100-ZIDCODE, "회원 ID
  ZMATNR TYPE ZEDT07_100-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_100-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_100-ZMTART, "제품유형
  ZMTART_NAME TYPE STR, "제품유형 이름
  ZVOLUM TYPE ZEDT07_100-ZVOLUM, "수량
  VRKME TYPE ZEDT07_100-VRKME,"단위
  ZNSAMT TYPE ZEDT07_100-ZNSAMT, "판매금액
  ZSLAMT TYPE ZEDT07_100-ZSLAMT, "매출금액
  ZDCAMT TYPE ZEDT07_100-ZDCAMT, "할인금액
  ZSALE_FG TYPE ZEDT07_100-ZSALE_FG, "매출구분
  ZSALE_FG_NAME TYPE STR, "매출구분 이름
  ZJDATE TYPE ZEDT07_100-ZJDATE, "판매일자
  ZRET_FG TYPE ZEDT07_100-ZRET_FG, "반품구분
  ZRET_FG_NAME TYPE STR, "반품구분 이름
  ZRDATE TYPE ZEDT07_100-ZRDATE, "반품일
  END OF GS_ORDER_ALV.
DATA : GT_ORDER_ALV LIKE TABLE OF GS_ORDER_ALV. "인터널테이블

"배송내역 구조체
DATA : BEGIN OF GS_DELIVERY,
  ZORDNO TYPE ZEDT07_101-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_101-ZIDCODE, "회원ID
  ZMATNR TYPE ZEDT07_101-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_101-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_101-ZMTART, "제품유형
  ZVOLUM TYPE ZEDT07_101-ZVOLUM, "수량
  VRKME TYPE ZEDT07_101-VRKME, "단위
  ZSLAMT TYPE ZEDT07_101-ZSLAMT, "매출금액
  ZDFLAG TYPE ZEDT07_101-ZDFLAG, "배송현황
  ZDGUBUN TYPE ZEDT07_101-ZDGUBUN, "배송지역
  ZDDATE TYPE ZEDT07_101-ZDDATE, "배송일자
  ZRDATE TYPE ZEDT07_101-ZRDATE, "반품일자
  ZFLAG TYPE ZEDT07_101-ZFLAG, "반품표시
END OF GS_DELIVERY.
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.

"배송내역 ALV출력용
DATA : BEGIN OF GS_DELIVERY_ALV,
  ZCOLOR TYPE C LENGTH 4, "신호등 색상을 표기하기 위한 변수
  ZORDNO TYPE ZEDT07_101-ZORDNO, "주문번호
  ZIDCODE TYPE ZEDT07_101-ZIDCODE, "회원ID
  ZMATNR TYPE ZEDT07_101-ZMATNR, "제품번호
  ZMATNAME TYPE ZEDT07_101-ZMATNAME, "제품명
  ZMTART TYPE ZEDT07_101-ZMTART, "제품유형
  ZMTART_NAME TYPE STR, "제품유형 이름
  ZVOLUM TYPE ZEDT07_101-ZVOLUM, "수량
  VRKME TYPE ZEDT07_101-VRKME, "단위
  ZSLAMT TYPE ZEDT07_101-ZSLAMT, "매출금액
  ZDFLAG TYPE ZEDT07_101-ZDFLAG, "배송현황
  ZDFLAG_NAME TYPE STR, "배송현황 이름
  ZDGUBUN TYPE ZEDT07_101-ZDGUBUN, "배송지역
  ZDGUBUN_NAME TYPE STR, "배송지역 이름
  ZDDATE TYPE ZEDT07_101-ZDDATE, "배송일자
  ZRDATE TYPE ZEDT07_101-ZRDATE, "반품일자
  ZFLAG TYPE ZEDT07_101-ZFLAG, "반품표시
END OF GS_DELIVERY_ALV.
DATA : GT_DELIVERY_ALV LIKE TABLE OF GS_DELIVERY_ALV. "인터널테이블

"OK-CODE
DATA : OK_CODE TYPE SY-UCOMM.

"도킹 컨테이너 객체 변수 선언
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

"그리드 객체 변수 선언
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

"필드 카탈로그
DATA : GS_FIELDCAT TYPE LVC_S_FCAT.
DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

"정렬
DATA : GS_SORT TYPE LVC_S_SORT.
DATA : GT_SORT TYPE LVC_T_SORT.

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO.

"이벤트 변수
DATA : GO_EVENT TYPE REF TO EVENT.
