*&---------------------------------------------------------------------*
*& Report ZEDR07_067
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_067.


SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
*PARAMETERS : P_ZCODE LIKE ZEDT07_001-ZCODE LOWER CASE. "소문자로 입력받기
PARAMETERS : P_ZCODE LIKE ZEDT07_001-ZCODE.
PARAMETERS : P_ZPERNE TYPE C LENGTH 10 NO-DISPLAY. "숨김 처리
*PARAMETERS : P_ZNUM TYPE P DECIMALS 2.
PARAMETERS : P_ZGEN LIKE ZEDT07_001-ZGENDER DEFAULT 'M'. "변수의 초기값 설정
SELECTION-SCREEN END OF BLOCK B1.


SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
"체크 버튼
PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.
  SELECTION-SCREEN BEGIN OF LINE.

  "라디오 버튼
  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.
SELECTION-SCREEN POSITION 3.
SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.
SELECTION-SCREEN POSITION 20.
SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B3.

"체크 버튼에 따른 출력물 구분
IF Z_CHECK = 'X'.
  WRITE :/ '체크 버튼 - 체크내역 출력'.
ELSE.
  WRITE :/ '체크 버튼 - 기타 출력'.
ENDIF.

"라디오버튼에 따라 출력문 구분
IF P_R1 = 'X'.
  WRITE :/ '라디오 버튼 - R1 체크내역 출력'.
ELSEIF P_R2 = 'X'.
  WRITE :/ '라디오 버튼 - R2 체크내역 출력'.
ENDIF.
