*&---------------------------------------------------------------------*
*& Report ZEDR07_008
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_008.

DATA : BEGIN OF GS_STUDENT,
  ZPERNR LIKE ZEDT07_001-ZPERNR,
  ZCODE LIKE ZEDT07_001-ZCODE,
  ZKNAME LIKE ZEDT07_001-ZKNAME,
  ZENAME LIKE ZEDT07_001-ZENAME,
  ZGENDER LIKE ZEDT07_001-ZGENDER,
  ZGNAME TYPE C LENGTH 4,
  ZTEL LIKE ZEDT07_001-ZTEL,
  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '감동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'A'.
GS_STUDENT-ZTEL = '01011112222'.

IF GS_STUDENT-ZGENDER = 'M'.
  GS_STUDENT-ZGNAME = '남자'.
ELSEIF GS_STUDENT-ZGENDER = 'F'.
  GS_STUDENT-ZGNAME = '여자'.
ELSE.
  GS_STUDENT-ZGNAME = '기타'.
  ENDIF.

APPEND GS_STUDENT TO GT_STUDENT.

BREAK-POINT.

CLEAR : GS_STUDENT.
