*&---------------------------------------------------------------------*
*&  Include           ZEDR07_HW001_SCR
*&---------------------------------------------------------------------*

"검색 정보 입력
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  SELECT-OPTIONS : S_ZORDNO FOR ZEDT07_100-ZORDNO. "주문번호
  SELECT-OPTIONS : S_ZID FOR ZEDT07_100-ZIDCODE NO INTERVALS NO-EXTENSION. "회원ID
  SELECT-OPTIONS : S_ZMATNR FOR ZEDT07_100-ZMATNR. "제품번호
  SELECT-OPTIONS : S_ZJDATE FOR ZEDT07_100-ZJDATE MODIF ID M1. "주문일자(판매일자)
  SELECT-OPTIONS : S_ZDDATE FOR ZEDT07_101-ZDDATE MODIF ID M2. "배송날짜(배송일자)
SELECTION-SCREEN END OF BLOCK B1.

"라디오 버튼 입력
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 USER-COMMAND UC1 DEFAULT 'X'. "주문내역
  PARAMETERS : P_R2 RADIOBUTTON GROUP R1. "배송내역
SELECTION-SCREEN END OF BLOCK B2.

"반품내역 포함  체크박스
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.
  PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B3.
