*&---------------------------------------------------------------------*
*& Report ZEDR07_068
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR07_068.

DATA : BEGIN OF GS_STUDENT,
  ZCODE TYPE ZEDT07_001-ZCODE,
  ZGENDER TYPE ZEDT07_001-ZGENDER,
  END OF GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
PARAMETERS : P_ZCODE LIKE ZEDT07_001-ZCODE.
PARAMETERS : P_ZPERNE TYPE C LENGTH 10 NO-DISPLAY.
PARAMETERS : P_ZGEN LIKE ZEDT07_001-ZGENDER DEFAULT 'M'.
SELECTION-SCREEN END OF BLOCK B1.

SELECT * FROM ZEDT07_001
  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT
  WHERE ZCODE = P_ZCODE
  AND ZGENDER = P_ZGEN.

IF GT_STUDENT[] IS NOT INITIAL.
  WRITE :/ '데이터 있음'.
  WRITE :/ P_ZCODE, P_ZGEN.
ELSE.
  WRITE :/ '데이터 없음'.
  WRITE :/ P_ZCODE, P_ZGEN.
ENDIF.
